version: '3'

networks:
  backend:
  traefik:
    external: true

services:

  elastic:
    image: elasticsearch:7.9.3
    volumes:
      - /swarm/bai-systems/el-data:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  logstash:
    image: logstash:7.9.3
    environment:
      - monitoring.elasticsearch.hosts=http://elastic:9200
    volumes:
      - /swarm/bai-systems/logstash-config:/usr/share/logstash/config/
    networks:
      - backend


  