version: '3'

networks:
  bai-backend:
    external: true
  traefik:
    external: true
  backend:

services:

  elastic:
    image: elasticsearch:7.9.3
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /swarm/bai-systems/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  logstash:
    image: logstash:7.9.3
    volumes:
      - ./config/logstash/sensors_api.conf:/usr/share/logstash/pipeline/sensors_api.conf
    networks:
      - bai-backend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  kibana:
    image: kibana:7.9.3
    volumes:
      - ./config/kibana/kibana.yml.local:/usr/share/kibana/config/kibana.yml
    networks:
      - backend
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bai-systems-kibana.entrypoints=web"
        - "traefik.http.routers.bai-systems-kibana.rule=Host(`kibana.bai-systems.cf`)"
        - "traefik.http.routers.bai-systems-kibana.middlewares=redirect-https@file"
        - "traefik.http.routers.bai-systems-kibana-https.tls=true"
        - "traefik.http.routers.bai-systems-kibana-https.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.bai-systems-kibana-https.entrypoints=websecure"
        - "traefik.http.routers.bai-systems-kibana-https.rule=Host(`kibana.bai-systems.cf`)"
        - "traefik.http.services.bai-systems-kibana.loadbalancer.server.port=5601"