version: '3'

networks:
  backend:
  traefik:
    external: true

services:

  sensors_api:
    image: riipeckx/bai-systems-smart-api-rest-python:latest
    networks:
      - backend

  web:
    image: b4bz/homer
    networks:
      - traefik
    volumes:
      - /swarm/bai-systems/web/:/www/assets
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bai-systems-web.entrypoints=web"
      - "traefik.http.routers.bai-systems-web.rule=Host(`bai-systems.cf`)"
      - "traefik.http.routers.bai-systems-web.middlewares=redirect-https@file"
      - "traefik.http.routers.bai-systems-web-https.tls=true"
      - "traefik.http.routers.bai-systems-web-https.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.bai-systems-web-https.entrypoints=websecure"
      - "traefik.http.routers.bai-systems-web-https.rule=Host(`bai-systems.cf`)"
      - "traefik.http.services.bai-systems-web.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == worker

  elastic:
    image: elasticsearch:7.9.3
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /swarm/bai-systems/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  logstash:
    image: logstash:7.9.3
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipelines/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash/api.conf:/etc/logstash/conf.d/api.conf
      - /swarm/bai-systems/logstash/data:/usr/share/logstash/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  kibana:
    image: kibana:7.9.3
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - backend
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bai-systems-kibana.entrypoints=web"
        - "traefik.http.routers.bai-systems-kibana.rule=Host(`kibana.bai-systems.cf`)"
        - "traefik.http.routers.bai-systems-kibana.middlewares=redirect-https@file"
        - "traefik.http.routers.bai-systems-kibana-https.tls=true"
        - "traefik.http.routers.bai-systems-kibana-https.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.bai-systems-kibana-https.entrypoints=websecure"
        - "traefik.http.routers.bai-systems-kibana-https.rule=Host(`kibana.bai-systems.cf`)"
        - "traefik.http.services.bai-systems-kibana.loadbalancer.server.port=5601"