server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elastic:9200" ]

elasticsearch.username: "kibana_system"
elasticsearch.password: "password"

xpack.security.encryptionKey: "encryptionKey"

xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"