server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elastic:9200" ]

elasticsearch.username: "kibana_system"
elasticsearch.password: "512f832CF4*"

xpack.security.encryptionKey: "QDwi9G5bYfvW2EHgj2djtCDd55Y4zryN"

xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"